// ============================================
// Talkify - Turkish UI Strings
// ============================================

export const Strings = {
  app: {
    name: 'Talkify',
    tagline: 'WhatsApp sohbetlerini analiz et!',
  },

  tabs: {
    home: 'Ana Sayfa',
    analysis: 'Analiz',
    statistics: 'İstatistik',
    settings: 'Gizlilik',
  },

  home: {
    title: 'Sohbet Yükle',
    subtitle: 'WhatsApp sohbet dosyanı yükle ve analiz et',
    uploadButton: 'Dosya Seç',
    uploadHint: 'WhatsApp > Sohbet > Dışa Aktar > Medyasız',
    recentChats: 'Son Yüklenen',
    noChats: 'Henüz bir sohbet yüklenmedi',
    parsing: 'Sohbet okunuyor...',
    detecting: 'Format algılanıyor...',
    classifying: 'Mesajlar sınıflandırılıyor...',
    done: 'Tamamlandı!',
    error: 'Bir hata oluştu',
  },

  analysis: {
    title: 'Analiz Sonuçları',
    subtitle: 'AI ile sohbet analizi',
    startAnalysis: 'Analizi Başlat',
    analyzing: 'Analiz ediliyor...',
    noData: 'Önce bir sohbet dosyası yükleyin',
    noConnection: 'LLM bağlantısı kurulamadı',
    nickname: 'Lakap',
    personality: 'Kişilik',
    gossip: 'Dedikodu',
    warning: 'Uyarı',
    groupDynamics: 'Grup Dinamikleri',
    participantAnalysis: 'Katılımcı Analizi',
    funFacts: 'Eğlenceli Bilgiler',
    retry: 'Tekrar Dene',
  },

  statistics: {
    title: 'İstatistikler',
    subtitle: 'Sohbet istatistikleri',
    noData: 'Önce bir sohbet dosyası yükleyin',
    totalMessages: 'Toplam Mesaj',
    totalWords: 'Toplam Kelime',
    totalEmojis: 'Toplam Emoji',
    totalMedia: 'Medya Dosyası',
    totalLinks: 'Paylaşılan Link',
    dateRange: 'Tarih Aralığı',
    mostActive: 'En Aktif',
    hourlyActivity: 'Saatlik Aktivite',
    dailyActivity: 'Günlük Aktivite',
    topEmojis: 'En Çok Kullanılan Emojiler',
    participants: 'Katılımcılar',
    messageDistribution: 'Mesaj Dağılımı',
    behaviorPatterns: 'Davranış Desenleri',
    avgResponseTime: 'Ort. Yanıt Süresi',
    minutes: 'dakika',
  },

  settings: {
    title: 'Gizlilik',
    llmSection: 'Groq AI Ayarları',
    groqApiKey: 'Groq API Anahtarı',
    groqApiKeyPlaceholder: 'gsk_...',
    groqModel: 'Model',
    envHint: '.env dosyasından API anahtarı kullanılıyor',
    testConnection: 'Bağlantıyı Test Et',
    connected: 'Bağlı',
    disconnected: 'Bağlantı yok',
    connecting: 'Bağlanıyor...',
    about: 'Hakkında',
    version: 'Versiyon',
    privacy: 'Gizlilik',
    privacyNote: 'Sohbet verileri analiz için Groq sunucularına gönderilir. Veriler Groq tarafında saklanmaz.',
  },

  patterns: {
    gece_kusu: 'Gece Kuşu',
    monolog_krali: 'Monolog Kralı',
    hayalet: 'Hayalet',
    emoji_ustasi: 'Emoji Ustası',
    sohbet_atesleyici: 'Sohbet Ateşleyicisi',
    tek_kelimelik: 'Tek Kelimelik Cevapçı',
    link_bombardimanci: 'Link Bombardımancısı',
    soru_makinesi: 'Soru Makinesi',
    roman_yazari: 'Roman Yazarı',
    sessiz_okuyucu: 'Sessiz Okuyucu',
    sabahci: 'Sabahçı',
    medya_delisi: 'Medya Delisi',
  },

  patternDescriptions: {
    gece_kusu: 'Gece yarısından sonra aktif olma oranı yüksek',
    monolog_krali: 'Üst üste çok sayıda mesaj gönderme eğiliminde',
    hayalet: 'Yanıt süresi ortalamanın çok üzerinde',
    emoji_ustasi: 'Çok çeşitli ve bol emoji kullanıyor',
    sohbet_atesleyici: 'Konuşmaları başlatan kişi',
    tek_kelimelik: 'Genellikle kısa, tek kelimelik yanıtlar veriyor',
    link_bombardimanci: 'Sürekli link paylaşıyor',
    soru_makinesi: 'Çok fazla soru soruyor',
    roman_yazari: 'Uzun, detaylı mesajlar yazıyor',
    sessiz_okuyucu: 'Grubun en az aktif üyesi',
    sabahci: 'Sabah saatlerinde çok aktif',
    medya_delisi: 'Bol bol fotoğraf ve video paylaşıyor',
  },

  patternIcons: {
    gece_kusu: '🦉',
    monolog_krali: '👑',
    hayalet: '👻',
    emoji_ustasi: '🎨',
    sohbet_atesleyici: '🔥',
    tek_kelimelik: '💬',
    link_bombardimanci: '🔗',
    soru_makinesi: '❓',
    roman_yazari: '📖',
    sessiz_okuyucu: '🤫',
    sabahci: '🌅',
    medya_delisi: '📸',
  },

  days: ['Pazar', 'Pazartesi', 'Salı', 'Çarşamba', 'Perşembe', 'Cuma', 'Cumartesi'],
  daysShort: ['Paz', 'Pzt', 'Sal', 'Çar', 'Per', 'Cum', 'Cmt'],

  common: {
    loading: 'Yükleniyor...',
    error: 'Hata',
    retry: 'Tekrar Dene',
    cancel: 'İptal',
    save: 'Kaydet',
    delete: 'Sil',
    close: 'Kapat',
    confirm: 'Onayla',
    messages: 'mesaj',
    words: 'kelime',
  },
} as const;
